# Generated by Django 5.2.5 on 2025-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
