# Generated by Django 5.2.5 on 2025-09-09 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0002_evento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
