# Generated by Django 5.2.5 on 2025-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0003_remove_evento_fecha_hora_evento_fecha_evento_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gestion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
