# Generated by Django 5.2.5 on 2025-09-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion', '0002_convocatoria_fechaconvocatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofechaconvocatoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
