# Generated by Django 5.2.5 on 2025-09-03 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion', '0003_archivofechaconvocatoria_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaconvocatoria',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
