# Generated by Django 5.2.5 on 2025-09-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion', '0004_fechaconvocatoria_hora_inicio'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaconvocatoria',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fecha_convocatoria', to='django_celery_beat.periodictask'),
        ),
    ]
