# Generated by Django 5.2.5 on 2025-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion', '0005_fechaconvocatoria_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='fecha_confirmacion_recepcion_convocatoria',
            field=models.DateField(blank=True, help_text='Fecha en que se confirmó la recepción de la convocatoria.', null=True),
        ),
    ]
