# Generated by Django 5.2.5 on 2025-09-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('preparacion', '0004_asesoramiento_capacitacion_empresa_asesoramientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='preparacion.empresa'),
        ),
    ]
