# Generated by Django 5.2.5 on 2025-09-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_is_active'),
        ('preparacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='preparacion.empresa'),
        ),
    ]
