# Generated by Django 5.2.5 on 2025-09-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_empresa'),
        ('accounts', '0006_user_is_online'),
    ]

    operations = [
    ]
