# Generated by Django 5.2.5 on 2025-09-06 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('file', 'Archivo')], max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='requisitos.requisito')),
            ],
        ),
        migrations.AddField(
            model_name='requisito',
            name='tipoSello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='requisitos.tiposello'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('gestion', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('NOTIFICADO', 'Notificado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='NOTIFICADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_evaluacion', models.ManyToManyField(related_name='evaluaciones', to='requisitos.checklistevaluacion')),
                ('evaluadores', models.ManyToManyField(limit_choices_to={'role__name': 'Evaluador'}, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('tipoSello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='requisitos.tiposello')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requisito',
            unique_together={('tipoSello', 'gestion', 'nombre')},
        ),
    ]
