# Generated by Django 5.2.5 on 2025-09-09 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0002_empresa_isaproved_empresa_tiposello'),
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('tipoSello', 'gestion')},
        ),
        migrations.AddField(
            model_name='checklistevaluacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistevaluacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluacion_asignada', to='preparacion.empresa'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requisitoinput',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checklistevaluacion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checklistevaluacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='EvaluacionFases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('gestion', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='requisitos.evaluacion')),
            ],
            options={
                'verbose_name': 'Fase de Evaluación',
                'verbose_name_plural': 'Fases de Evaluación',
            },
        ),
        migrations.AddField(
            model_name='checklistevaluacion',
            name='evaluacion_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='requisitos.evaluacionfases'),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='checklist_evaluacion',
        ),
    ]
