# Generated by Django 5.2.5 on 2025-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0002_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionfases',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
