# Generated by Django 5.2.5 on 2025-09-19 07:51

import django.db.models.deletion
import requisitos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0003_evaluacionfases_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoInputValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=10)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_archivo', models.FileField(blank=True, null=True, upload_to=requisitos.models.requisito_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requisito_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='requisitos.requisitoinput')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_requisito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'requisito_input', 'gestion')},
            },
        ),
    ]
