# Generated by Django 5.2.5 on 2025-09-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0004_requisitoinputvalor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitoinputvalor',
            old_name='valor_archivo',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='requisitoinputvalor',
            old_name='valor_texto',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='requisitoinputvalor',
            name='valor_fecha',
        ),
        migrations.RemoveField(
            model_name='requisitoinputvalor',
            name='valor_numero',
        ),
    ]
