# Generated by Django 5.2.5 on 2025-09-20 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0003_faseempresa'),
        ('requisitos', '0005_rename_valor_archivo_requisitoinputvalor_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistevaluacion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EvaluacionDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('gestion', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_datos', to='requisitos.checklistevaluacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_datos', to='preparacion.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_datos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato de Evaluación',
                'verbose_name_plural': 'Datos de Evaluación',
                'unique_together': {('usuario', 'checklist_evaluacion', 'gestion')},
            },
        ),
    ]
