# Generated by Django 5.2.5 on 2025-09-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0003_faseempresa'),
        ('requisitos', '0006_checklistevaluacion_is_required_evaluaciondato'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requisitoinputvalor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='requisitoinputvalor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_requisito_empresa', to='preparacion.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitoinputvalor',
            unique_together={('empresa', 'requisito_input', 'gestion')},
        ),
    ]
