# Generated by Django 5.2.5 on 2025-09-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0007_alter_requisitoinputvalor_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionfases',
            name='evaluador',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Evaluador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases_evaluador', to=settings.AUTH_USER_MODEL),
        ),
    ]
