# Generated by Django 5.2.5 on 2025-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0008_evaluacionfases_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
