# Generated by Django 5.2.5 on 2025-09-26 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0008_alter_empresa_nit'),
        ('requisitos', '0009_enlaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluaciondato',
            unique_together={('usuario', 'checklist_evaluacion', 'gestion', 'empresa')},
        ),
    ]
