# Generated by Django 5.2.5 on 2025-09-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0001_initial'),
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='isAproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipoSello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='requisitos.tiposello'),
        ),
    ]
