# Generated by Django 5.2.5 on 2025-09-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0002_empresa_isaproved_empresa_tiposello'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_numero', models.IntegerField(default=1, help_text='Número que representa la fase actual de la empresa.')),
                ('gestion', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_empresa', to='preparacion.empresa')),
            ],
        ),
    ]
