# Generated by Django 5.2.5 on 2025-09-23 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0003_faseempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='asesoramientos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='capacitaciones/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='asesoramientos',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='preparacion.asesoramiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='capacitaciones',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='preparacion.capacitacion'),
        ),
        migrations.CreateModel(
            name='PublicacionEmpresaComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fotourl', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_comunidad', to='preparacion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAsesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsesoramiento', models.CharField(max_length=255)),
                ('fechaTentativaInicial', models.DateField()),
                ('fechaTentativaFinal', models.DateField()),
                ('fechaAprobada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesoramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='preparacion.asesoramiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asesoramiento', to='preparacion.empresa')),
            ],
        ),
    ]
