# Generated by Django 5.2.5 on 2025-09-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0004_asesoramiento_capacitacion_empresa_asesoramientos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faseempresa',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases_empresa_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudasesoramiento',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
    ]
