# Generated by Django 5.2.5 on 2025-09-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0005_faseempresa_evaluador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAsesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='asesoramientos/files/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asesoramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='preparacion.asesoramiento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EncargadoAsesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asesoramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargados_asesoramiento', to='preparacion.asesoramiento')),
            ],
        ),
    ]
