# Generated by Django 5.2.5 on 2025-09-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0006_archivoasesoramiento_encargadoasesoramiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionempresacomunidad',
            name='fotourl',
        ),
        migrations.AddField(
            model_name='publicacionempresacomunidad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/fotos/'),
        ),
    ]
