# Generated by Django 5.2.5 on 2025-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0007_remove_publicacionempresacomunidad_fotourl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
