# Generated by Django 5.2.5 on 2025-09-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_messageattachment_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
